project:
  type: website
  output-dir: docs
website:
  title: "geed.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: trestles
    css: styles.css
    toc: true

editor: visual

